sudo: false
language: node_js
node_js: "7.9.0"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test
notifications:
  on_failure: change # always|never
  on_success: never
